# Generated by Django 4.0.4 on 2022-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
