# Generated by Django 4.0.4 on 2022-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pages_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='poster',
            field=models.ImageField(default='posters/def.jpg', upload_to='posters/'),
        ),
    ]
