# Generated by Django 4.0.4 on 2022-05-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_titles_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='banner',
            field=models.ImageField(default='banners/def.jpg', upload_to='banners/'),
        ),
    ]
