# Generated by Django 4.0.5 on 2022-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_titles_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='titles',
            name='origin_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
