# Generated by Django 4.0.5 on 2022-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_titles_slug_alter_titles_origin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='number',
            field=models.FloatField(),
        ),
    ]
