# Generated by Django 4.0.5 on 2022-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_books_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='origin_id',
            field=models.IntegerField(unique=True),
        ),
    ]
