# Generated by Django 4.0.5 on 2022-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_books_origin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
