# Generated by Django 4.0.5 on 2022-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_pages_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
